// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9lguaAG2nDI9E48_LiP9yo8IHlLvvygA',
    appId: '1:728518331859:web:9eacf8b92839095a0bf326',
    messagingSenderId: '728518331859',
    projectId: 'unumbers-bbac2',
    authDomain: 'unumbers-bbac2.firebaseapp.com',
    storageBucket: 'unumbers-bbac2.firebasestorage.app',
    measurementId: 'G-ZSB4CSFSQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaJ3RE5lk6RqDWBMHcdqiGBgdVVm0roxU',
    appId: '1:728518331859:android:f34cc6e7bdb804980bf326',
    messagingSenderId: '728518331859',
    projectId: 'unumbers-bbac2',
    storageBucket: 'unumbers-bbac2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT0uw10NUl5Hlamu1f40SprCQx01USAG0',
    appId: '1:728518331859:ios:4062bddb8abb44280bf326',
    messagingSenderId: '728518331859',
    projectId: 'unumbers-bbac2',
    storageBucket: 'unumbers-bbac2.firebasestorage.app',
    iosBundleId: 'com.example.unumbers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT0uw10NUl5Hlamu1f40SprCQx01USAG0',
    appId: '1:728518331859:ios:4062bddb8abb44280bf326',
    messagingSenderId: '728518331859',
    projectId: 'unumbers-bbac2',
    storageBucket: 'unumbers-bbac2.firebasestorage.app',
    iosBundleId: 'com.example.unumbers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9lguaAG2nDI9E48_LiP9yo8IHlLvvygA',
    appId: '1:728518331859:web:e9feeb2a692f12c00bf326',
    messagingSenderId: '728518331859',
    projectId: 'unumbers-bbac2',
    authDomain: 'unumbers-bbac2.firebaseapp.com',
    storageBucket: 'unumbers-bbac2.firebasestorage.app',
    measurementId: 'G-D3GB1VHN7R',
  );

}